package org.viktorisa.demoapp.domain;

import java.io.Serializable;
import java.util.Date;

public class DemoUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.id
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_id
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.user_name
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.password
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.is_active
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.is_admin
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Boolean isAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.created_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.last_updated_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Integer lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.createdAt
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Date createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.updatedAt
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Date updatedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.last_update_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_user.creation_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.id
     *
     * @return the value of demo_user.id
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.id
     *
     * @param id the value for demo_user.id
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_id
     *
     * @return the value of demo_user.user_id
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_id
     *
     * @param userId the value for demo_user.user_id
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.user_name
     *
     * @return the value of demo_user.user_name
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.user_name
     *
     * @param userName the value for demo_user.user_name
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.password
     *
     * @return the value of demo_user.password
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.password
     *
     * @param password the value for demo_user.password
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.is_active
     *
     * @return the value of demo_user.is_active
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.is_active
     *
     * @param isActive the value for demo_user.is_active
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.is_admin
     *
     * @return the value of demo_user.is_admin
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Boolean getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.is_admin
     *
     * @param isAdmin the value for demo_user.is_admin
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.created_by
     *
     * @return the value of demo_user.created_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.created_by
     *
     * @param createdBy the value for demo_user.created_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.last_updated_by
     *
     * @return the value of demo_user.last_updated_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Integer getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.last_updated_by
     *
     * @param lastUpdatedBy the value for demo_user.last_updated_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setLastUpdatedBy(Integer lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.createdAt
     *
     * @return the value of demo_user.createdAt
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.createdAt
     *
     * @param createdat the value for demo_user.createdAt
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.updatedAt
     *
     * @return the value of demo_user.updatedAt
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.updatedAt
     *
     * @param updatedat the value for demo_user.updatedAt
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.last_update_date
     *
     * @return the value of demo_user.last_update_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.last_update_date
     *
     * @param lastUpdateDate the value for demo_user.last_update_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_user.creation_date
     *
     * @return the value of demo_user.creation_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_user.creation_date
     *
     * @param creationDate the value for demo_user.creation_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
}