package org.viktorisa.demoapp.domain;

import java.io.Serializable;
import java.util.Date;

public class DemoTask implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.task_id
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.task_name
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.task_description
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private String taskDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.assignee
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Integer assignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.assign_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Integer assignBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.finish_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Date finishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.last_updated_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Integer lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.last_update_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.created_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.creation_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demo_task
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.task_id
     *
     * @return the value of demo_task.task_id
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.task_id
     *
     * @param taskId the value for demo_task.task_id
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.task_name
     *
     * @return the value of demo_task.task_name
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.task_name
     *
     * @param taskName the value for demo_task.task_name
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.task_description
     *
     * @return the value of demo_task.task_description
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public String getTaskDescription() {
        return taskDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.task_description
     *
     * @param taskDescription the value for demo_task.task_description
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription == null ? null : taskDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.assignee
     *
     * @return the value of demo_task.assignee
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Integer getAssignee() {
        return assignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.assignee
     *
     * @param assignee the value for demo_task.assignee
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setAssignee(Integer assignee) {
        this.assignee = assignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.assign_by
     *
     * @return the value of demo_task.assign_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Integer getAssignBy() {
        return assignBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.assign_by
     *
     * @param assignBy the value for demo_task.assign_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setAssignBy(Integer assignBy) {
        this.assignBy = assignBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.finish_date
     *
     * @return the value of demo_task.finish_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.finish_date
     *
     * @param finishDate the value for demo_task.finish_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.last_updated_by
     *
     * @return the value of demo_task.last_updated_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Integer getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.last_updated_by
     *
     * @param lastUpdatedBy the value for demo_task.last_updated_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setLastUpdatedBy(Integer lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.last_update_date
     *
     * @return the value of demo_task.last_update_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.last_update_date
     *
     * @param lastUpdateDate the value for demo_task.last_update_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.created_by
     *
     * @return the value of demo_task.created_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.created_by
     *
     * @param createdBy the value for demo_task.created_by
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.creation_date
     *
     * @return the value of demo_task.creation_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.creation_date
     *
     * @param creationDate the value for demo_task.creation_date
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
}