package org.viktorisa.demoapp.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.viktorisa.demoapp.domain.DemoUser;
import org.viktorisa.demoapp.domain.DemoUserExample;

public interface DemoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    int countByExample(DemoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    int deleteByExample(DemoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    int insert(DemoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    int insertSelective(DemoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    List<DemoUser> selectByExample(DemoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    DemoUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    int updateByExampleSelective(@Param("record") DemoUser record, @Param("example") DemoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    int updateByExample(@Param("record") DemoUser record, @Param("example") DemoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    int updateByPrimaryKeySelective(DemoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_user
     *
     * @mbggenerated Fri Mar 18 01:22:13 WIB 2016
     */
    int updateByPrimaryKey(DemoUser record);
}